### ISSUE TITLE
通知メール送信処理(バッチ)の実装

### ISSUE THREAD

**Issue by kawanamiyuu** [TeijigoTeaTime/meshido-backend#12]
### 機能の概要

ランチ｜ディナーへの参加者にメールで通知する
### 要件（＝このIssueでやること）
- 参加人数が **2人以上** の場合に通知する
- **11時** に、その日の **ランチ** の参加登録者にメール通知する
- **17時** に、その日の **ディナー** の参加登録者にメール通知する
- メール本文には、参加登録者全員の名前とメアドを記載する
  - →参加者同時が連絡し合えるようにする
### スコープ外の要件（＝このIssueではやらないこと）
- ...
- ...
- ...
## その他備考
- メール送信エンジンには `SendGrid` (Herokuアドオン) を使用する
- SendGridのAPIキーは環境変数で指定する

**Comment by kawanamiyuu** [comment]
@takayukifujisawa これ引き受けます

**Comment by takayukifujisawa** [comment]
おお…助かります。。もう死ぬかと
